In [1]:
import numpy as np
import cv2
import matplotlib.image as matimg
from PIL import Image
import matplotlib.pyplot as plt

In [2]:
#opencv -BGR - numpy array
img_cv = cv2.imread('./data/flying_bird.jpg')

In [3]:
print(img_cv)

None


In [5]:
# Matplotlib - RGB - numpy array
img_mat = matimg.imread('./data/flying_bird.jpg')

In [6]:
print(img_mat)

[[[ 92  48  21]
  [ 90  46  19]
  [ 88  42  16]
  ...
  [ 13  14   0]
  [ 10  11   0]
  [ 14  15   0]]

 [[ 88  44  17]
  [ 87  43  16]
  [ 87  41  15]
  ...
  [ 19  20   4]
  [ 16  17   1]
  [ 12  13   0]]

 [[ 91  45  19]
  [ 91  45  19]
  [ 91  45  19]
  ...
  [ 21  22   6]
  [ 22  23   7]
  [ 14  15   0]]

 ...

 [[ 88  56  31]
  [ 95  63  38]
  [ 97  65  40]
  ...
  [ 77 101   3]
  [ 74  98   0]
  [ 73  97   1]]

 [[ 93  61  36]
  [ 94  64  38]
  [ 95  65  39]
  ...
  [ 77 101   3]
  [ 75  99   1]
  [ 73  97   1]]

 [[ 92  62  36]
  [ 90  60  34]
  [ 90  60  34]
  ...
  [ 75  99   1]
  [ 73  97   0]
  [ 73  97   1]]]


In [7]:
# PIL - RGB - object
img_pil = Image.open('./data/flying_bird.jpg')